"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

type Option = { id: string; name: string; type?: string; account_type?: string };
export function TransactionForm({ memberId, householdId, accounts, categories }: { memberId: string; householdId: string; accounts: Option[]; categories: Option[] }) {
  const [type, setType] = useState<"income" | "expense">("expense"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const supabase = createClient(); const { error: insertError } = await supabase.from("transactions").insert({ household_id: householdId, member_id: memberId, account_id: String(data.get("account_id")), category_id: String(data.get("category_id")), transaction_type: type, amount: Number(data.get("amount")), transaction_date: String(data.get("transaction_date")), note: String(data.get("note") || "") }); if (insertError) { setError(insertError.message); setLoading(false); return; } router.push("/transaksi"); router.refresh(); }
  const filteredCategories = categories.filter((category) => category.type === type);
  return <form className="form-panel" onSubmit={submit}><div className="segmented"><button type="button" className={type === "expense" ? "selected" : ""} onClick={() => setType("expense")}>Pengeluaran</button><button type="button" className={type === "income" ? "selected" : ""} onClick={() => setType("income")}>Pemasukan</button></div><label className="field-label">Jumlah<input name="amount" type="number" min="1" step="1" required placeholder="0" /></label><div className="form-grid"><label className="field-label">Kategori<select name="category_id" required><option value="">Pilih kategori</option>{filteredCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="field-label">Akun<select name="account_id" required><option value="">Pilih akun</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></label></div><label className="field-label">Tanggal<input name="transaction_date" type="date" required defaultValue={new Date().toISOString().slice(0, 10)} /></label><label className="field-label">Catatan <span className="muted">(opsional)</span><textarea name="note" rows={3} placeholder="Contoh: makan siang bersama" /></label>{!accounts.length && <p className="error-text">Tambahkan akun terlebih dahulu di halaman Profil.</p>}{error && <p className="error-text">{error}</p>}<button className="primary-button" disabled={loading || !accounts.length}>{loading ? "Menyimpan..." : "Simpan transaksi"}</button></form>;
}