"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export function HouseholdSetup() {
  const [join, setJoin] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const router = useRouter();
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget); const householdName = String(data.get("household_name") || "").trim(); const supabase = createClient(); const { data: { user }, error: userError } = await supabase.auth.getUser(); if (userError || !user) { setError("Sesi masuk tidak ditemukan. Silakan masuk kembali."); setLoading(false); return; }
    if (join) { const response = await fetch("/api/household/join", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ inviteCode: data.get("invite_code") }) }); const result = await response.json(); if (!response.ok) { setError(result.error || "Household belum bisa diikuti."); setLoading(false); return; } } else { const inviteCode = crypto.randomUUID().replaceAll("-", "").slice(0, 6).toUpperCase(); const { data: householdResult, error: householdError } = await supabase.rpc("create_household", { household_name: householdName, new_invite_code: inviteCode }); if (householdError) { setError(householdError.message); setLoading(false); return; } if (householdResult?.already_exists) { setError("Akun ini sudah memiliki household aktif."); setLoading(false); return; } }
    router.push(`/dashboard?household=${encodeURIComponent(join ? "" : householdName)}`); router.refresh();
  }
  return <><h1>{join ? "Gabung ke ruangmu." : "Buat ruang keuangan."}</h1><p className="lede">{join ? "Masukkan kode undangan dari pasanganmu." : "Ruang ini bisa kamu bagikan dengan satu pengelola lain."}</p><div className="choice-row"><button className={!join ? "choice active" : "choice"} onClick={() => setJoin(false)} type="button">Buat baru</button><button className={join ? "choice active" : "choice"} onClick={() => setJoin(true)} type="button">Pakai kode</button></div><form onSubmit={submit} className="space-y-4">{!join && <label className="field-label">Nama household<input name="household_name" required placeholder="Contoh: Rumah Jomen & Dimas" /></label>}{join && <label className="field-label">Kode undangan<input name="invite_code" required maxLength={6} className="tracking-[.25em] uppercase" placeholder="A3F9K2" /></label>}<p className="muted text-sm">Nama tampilan akan diambil otomatis dari email akunmu.</p>{error && <p className="error-text">{error}</p>}<button type="submit" className="primary-button w-full" disabled={loading}>{loading ? "Menyimpan..." : join ? "Gabung sekarang" : "Buat household"}</button></form></>;
}